export type Lang = 'ar' | 'en'

const dict = {
  ar: {
    'app.name': 'دواء وشفاء',
    'app.tagline': 'منصة الأدوية والمرافق الطبية',
    'auth.signIn': 'تسجيل الدخول',
    'auth.signUp': 'إنشاء حساب',
    'auth.email': 'البريد الإلكتروني',
    'auth.password': 'كلمة المرور',
    'auth.name': 'الاسم الكامل',
    'auth.phone': 'رقم الهاتف',
    'auth.role': 'نوع الحساب',
    'auth.roleCitizen': 'مواطن',
    'auth.rolePharmacist': 'صيدلي',
    'auth.roleFacility': 'مرفق طبي',
    'auth.roleAdmin': 'أدمن',
    'auth.welcome': 'مرحباً بك',
    'auth.logout': 'تسجيل الخروج',
    'nav.home': 'الرئيسية',
    'nav.reports': 'البلاغات',
    'nav.chat': 'المحادثات',
    'nav.notifications': 'الإشعارات',
    'nav.profile': 'الملف',
    'report.technical': 'الإبلاغ عن مشكلة تقنية',
    'report.suggestion': 'تقديم اقتراح تطوير',
    'report.title': 'العنوان',
    'report.description': 'الوصف',
    'report.submit': 'إرسال',
    'report.cancel': 'إلغاء',
    'report.success': 'تم الإرسال بنجاح',
    'report.placeholderSuggestion': 'مثال: أقترح إضافة قسم الدعم النفسي في المنصة',
    'suggestion.section': 'اقتراحات لتطوير المنصة',
    'suggestion.title': 'عنوان الاقتراح',
    'chat.title': 'المحادثات',
    'chat.new': 'محادثة جديدة',
    'chat.subject': 'موضوع المحادثة',
    'chat.send': 'إرسال',
    'chat.placeholder': 'اكتب رسالتك...',
    'chat.noConversations': 'لا توجد محادثات بعد',
    'chat.open': 'فتح',
    'chat.close': 'إغلاق المحادثة',
    'chat.closed': 'مغلقة',
    'chat.adminName': 'فريق الإدارة',
    'admin.suggestions': 'الاقتراحات',
    'admin.conversations': 'المحادثات',
    'admin.filterByRole': 'فلترة حسب المرسل',
    'admin.allRoles': 'كل الأدوار',
    'admin.filterByDate': 'فلترة حسب التاريخ',
    'admin.reply': 'رد',
    'admin.noResults': 'لا توجد نتائج',
    'common.back': 'رجوع',
    'common.close': 'إغلاق',
    'common.loading': 'جارٍ التحميل...',
    'dash.citizen': 'لوحة المواطن',
    'dash.pharmacist': 'لوحة الصيدلي',
    'dash.facility': 'لوحة المرفق الطبي',
    'dash.admin': 'لوحة الأدمن',
  },
  en: {
    'app.name': 'Dawaa & Shifa',
    'app.tagline': 'Medicines & Medical Facilities Platform',
    'auth.signIn': 'Sign In',
    'auth.signUp': 'Sign Up',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.name': 'Full Name',
    'auth.phone': 'Phone Number',
    'auth.role': 'Account Type',
    'auth.roleCitizen': 'Citizen',
    'auth.rolePharmacist': 'Pharmacist',
    'auth.roleFacility': 'Medical Facility',
    'auth.roleAdmin': 'Admin',
    'auth.welcome': 'Welcome',
    'auth.logout': 'Log Out',
    'nav.home': 'Home',
    'nav.reports': 'Reports',
    'nav.chat': 'Chat',
    'nav.notifications': 'Notifications',
    'nav.profile': 'Profile',
    'report.technical': 'Report a Technical Issue',
    'report.suggestion': 'Submit a Suggestion',
    'report.title': 'Title',
    'report.description': 'Description',
    'report.submit': 'Submit',
    'report.cancel': 'Cancel',
    'report.success': 'Submitted successfully',
    'report.placeholderSuggestion': 'Example: I suggest adding a psychological support section to the platform',
    'suggestion.section': 'Suggestions for Platform Development',
    'suggestion.title': 'Suggestion Title',
    'chat.title': 'Conversations',
    'chat.new': 'New Conversation',
    'chat.subject': 'Conversation Subject',
    'chat.send': 'Send',
    'chat.placeholder': 'Type your message...',
    'chat.noConversations': 'No conversations yet',
    'chat.open': 'Open',
    'chat.close': 'Close Conversation',
    'chat.closed': 'Closed',
    'chat.adminName': 'Admin Team',
    'admin.suggestions': 'Suggestions',
    'admin.conversations': 'Conversations',
    'admin.filterByRole': 'Filter by Sender',
    'admin.allRoles': 'All Roles',
    'admin.filterByDate': 'Filter by Date',
    'admin.reply': 'Reply',
    'admin.noResults': 'No results',
    'common.back': 'Back',
    'common.close': 'Close',
    'common.loading': 'Loading...',
    'dash.citizen': 'Citizen Dashboard',
    'dash.pharmacist': 'Pharmacist Dashboard',
    'dash.facility': 'Facility Dashboard',
    'dash.admin': 'Admin Dashboard',
  },
} as const

export type TranslationKey = keyof typeof dict['ar']

export function useLang() {
  const lang: Lang = 'ar'
  const t = (key: TranslationKey): string => dict[lang][key] || key
  return { t, lang }
}
